INSERT INTO COUNTRIES (id, name) VALUES (1, 'USA');
INSERT INTO COUNTRIES (id, name) VALUES (2, 'France');
INSERT INTO COUNTRIES (id, name) VALUES (3, 'Brazil');
INSERT INTO COUNTRIES (id, name) VALUES (4, 'Italy');
INSERT INTO COUNTRIES (id, name) VALUES (5, 'Canada');